name: Flet Input Form
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to send data to.
    defaultValue: data-input
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: flet-input-form
